spring:
  application:
    name: currency-exchange
  cloud:
    config:
      enabled: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
    #sender:
      #type: rabbit

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 5
        waitDuration: 5s